### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by Zuckonit** [floragunncom/search-guard-kibana-plugin#1]
kibana version: 5.1.1
elasticsearch version: 5.1.1
search-guard-kibana-plugin version: 5.1.1-alpha.zip

```
Plugin installation was unsuccessful due to error "No valid url specified."
```

**Comment by floragunncom** [comment]
how did you install it?

**Comment by Zuckonit** [comment]
bin/kibana-plugin install  ./search-guard-kibana-plugin-5.1.1-alpha.zip

**Comment by floragunncom** [comment]
pls. try `bin/kibana-plugin install https://github.com/floragunncom/search-guard-kibana-plugin/releases/download/v5.1.1-alpha/searchguard-kibana-alpha-5.1.1.zip`

**Comment by rptete** [comment]
searchguard5 with compatibility to ES-5.1.2 and SGadmin10:
wget http://repo1.maven.org/maven2/com/floragunn/search-guard-5/5.1.2-10/search-guard-5-5.1.2-10.zip
/usr/share/elasticsearch/bin/elasticsearch-plugin install file:///root/search-guard-5-5.1.2-10.zip
/usr/share/elasticsearch/bin/elasticsearch-plugin list

searchguard5-kibanaPlugin with compatibility to KI-5.1.2
wget https://github.com/floragunncom/search-guard-kibana-plugin/releases/download/v5.1.2-alpha/searchguard-kibana-alpha-5.1.2.zip
/usr/share/kibana/bin/kibana-plugin install file:///root/searchguard-kibana-alpha-5.1.2.zip
/usr/share/kibana/bin/kibana-plugin list


4u players :)

Thanks to Marc Escamilla

**Comment by GaneshKudikala** [comment]
I have the same issue when I am instaling kibana plugin,
Error: Plugin installation was unsuccessful due to error "No valid url specified."

I tried with ./kibana-plugin install https://github.com/floragunncom/search-guard-kibana-plugin/archive/v6.3.0-16.zip

Downloaded in local directory and tried to  install  ./kibana-plugin install /tmp/search-guard-kibana-plugin-6.5.3-16.zip

./kibana-plugin install https://search.maven.org/artifact/com.floragunn/search-guard-kibana-plugin/6.5.3-16.zip


PLease help me to solve this

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard or, if you are a paying customer, contact our support.

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations or the issue will likely be closed as invalid:

* Search Guard and Elasticsearch version
* Kibana plugin version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug
* sg_*.yml config files
* kibana.yml file
* elasticsearch.yml file

These informations are optional but are very valuable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
