### ISSUE TITLE
KIBANA plugin installation stuck on "Optimizing and caching browser bundles..."

### ISSUE THREAD

**Issue by izvictor** [floragunncom/search-guard-kibana-plugin#101]
Hello,
I'm trying to install the search guard kibana plugin on Kiabana 6.3.0 and the plugin installation is stuck on "Optimizing and caching browser bundles..."
![image](https://user-images.githubusercontent.com/98562/42473520-288b053c-83c5-11e8-955b-a794cbbfe5be.png)
The KIBANA log file is saying:
```
{"type":"log","@timestamp":"2018-07-09T20:09:23Z","tags":["warning","config","deprecation"],"pid":3764,"message":"uiSettings.enabled is deprecated and is no longer used"}
{"type":"log","@timestamp":"2018-07-09T20:09:37Z","tags":["info","optimize"],"pid":3764,"message":"Optimizing and caching bundles for ml, stateSessionStorageRedirect, status_page, timelion, graph, monitoring, login, logout, dashboardViewer, apm, searchguard-login, searchguard-multitenancy, searchguard-configuration and kibana. This may take a few minutes"}
{"type":"log","@timestamp":"2018-07-09T20:13:07Z","tags":["info","optimize"],"pid":3764,"message":"Optimization of bundles for ml, stateSessionStorageRedirect, status_page, timelion, graph, monitoring, login, logout, dashboardViewer, apm, searchguard-login, searchguard-multitenancy, searchguard-configuration and kibana complete in 210.36 seconds"}
{"type":"log","@timestamp":"2018-07-09T20:13:07Z","tags":["info"],"pid":3764,"message":"Plugin initialization disabled."}
```

Can you please advise/help me with the installation please ?
Best regards.

**Comment by floragunncom** [comment]
The optimization step is a built-in Kibana process that you cannot skip. It was always painfully slow and you can find a lot of issues around this on the Elasticsearch forums. Now with 6.3.x the situation is even worse, since (if you don't download the pure OSS version) Kibana comes bundled with the X-Pack plugin. Which means both X-Pack and Search Guard need to go through the optimization process. On some machines, and also on Docker, we have seen that this process can take up to 10-15 minutes. It seems that Elasticsearch is working on improving this step, but at the moment there is nothing we can do from our side.

**Comment by izvictor** [comment]
Hello,
Thanks for taking time to answer me.
The problem is that the plugin installation is taking 9 hours now and nottill not finished. I activated the logging.verbose in kibana and no error messages are shown. 
Is there any way I can activate some debug level to see what's happening?
Thanks ...

**Comment by floragunncom** [comment]
9 hours is definitely not right. However, the optimization process is Kibana internal and cannot be switched off unfortunately. Have you tried to download the OSS version if Kibana (without X-Pack) and install Search Guard there?

**Comment by izvictor** [comment]
Didn't try the OSS version but found a post saying that all the x-pack features should be disabled in the kibana.yml in order for search guard to work.
So I have added the following config properties in the kibana.yml file:
```
xpack.monitoring.enabled: false
xpack.graph.enabled: false
xpack.ml.enabled: false
xpack.security.enabled: false
xpack.watcher.enabled: false
```
Well the plugin installation is still stuck at **Optimizing and caching browser bundles...** step , but after canceling the process and starting kibana the search guard seems to work and I have the login page displayed and all the search guard features are enabled.
The  **Optimizing and caching browser bundles...** step seems to silently broke when there is a conflict between search guard and x-pack I guess but not realy sure because no errors are shown in the log...
Any way I will go with the OSS version and search guard to avoid any other surprises ... 
Thanks for help.

**Comment by mazadard** [comment]
Hi, I have the exact same problem and exact same log. But the problem is not solved by canceling the process. I tried to remove and reinstall kibana and still doesn't work. 

Can you help me ? Thanks

**Comment by izvictor** [comment]
Hello,
Which version of kibana are you using 6.3.0 or 6.3.1 ?
Are you using Kibana OSS or Kiabana with X-Pack embedded ?
Have you disabled the x-pack features in the kiabna.yml ?
```
xpack.monitoring.enabled: false
xpack.graph.enabled: false
xpack.ml.enabled: false
xpack.security.enabled: false
xpack.watcher.enabled: false
```
Try launching the kibana process from command line by running the kibana.bat too see if no errors are shown in the std output...
Regards,

**Comment by mazadard** [comment]
I tried again and I guess this message: 

{"type":"log","@timestamp":"2018-07-09T20:13:07Z","tags":["info","optimize"],"pid":3764,"message":"Optimization of bundles for ml, stateSessionStorageRedirect, status_page, timelion, graph, monitoring, login, logout, dashboardViewer, apm, searchguard-login, searchguard-multitenancy, searchguard-configuration and kibana **complete in 210.36 seconds**"}

.. means that the install is finished, so I interrupted the minux process just after that and now it works.

**Comment by maghibus** [comment]
On the contrary using Kibana-oss it works.
Why?

**Comment by jochenkressin** [comment]
This is a well-known problem that Elastic is not really keen on fixing. The built-in optimize process is based on webpack and there always have been issues (mainly memory related), especially with Docker. You will find a lot on the ES/KI forum regarding this matter. The reason why the OSS flavor seems to work better is simply that the optimize process just needs to optimize the Search Guard plugin, and not the X-Pack plugin. When using the non-OSS version all X-Pack plugins plus Search Guard get optimized, leading to a huge amount of time and eventually OOM issues.
