### ISSUE TITLE
Support for Kibana 6.3.1

### ISSUE THREAD

**Issue by skipper00** [floragunncom/search-guard-kibana-plugin#105]
is kibana 6.3.1 supported?
thanks

**Comment by nicolas-f** [comment]
no.

```Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [searchguard]. Expected [6.3.1]; found [6.3.0]"```

**Comment by floragunncom** [comment]
Please see here for status: https://groups.google.com/forum/#!topic/search-guard/lTp5OB-011Q
