### ISSUE TITLE
Dots in regex should be allowed when configuring role's index-level permissions

### ISSUE THREAD

**Issue by occho** [floragunncom/search-guard-kibana-plugin#108]
## Issue

Regular expression is available for specifying index-level permissions for a role.

But, when setting a regular expression pattern including dots, the dots are replaced with `?` in the method [submitAddIndex](https://github.com/floragunncom/search-guard-kibana-plugin/blob/v6.3.1-14-beta-1/public/apps/configuration/sections/roles/controller.js#L382).

The pattern created after the replacement is not always a valid regular expression pattern, and can cause exceptions when trying to compiling the pattern.

For example, when specifying `/.*/` for the index input, it is converted to `/?*/`, which is an invalid regular expression.

## Versions

The versions I've experienced the issue with:
Elasticserch version: 6.3.1
SeachGuard ES plugin version: 6-6.3.1-22.3
Kibana version: 6.3.1
SearchGuard Kibana plugin version: 6.3.1-14-beta-1

This issue was originally posted in Search Guard Community Forum: https://groups.google.com/d/msg/search-guard/uoMi1_xqIE8/DMxLkIWMCAAJ

**Comment by floragunncom** [comment]
@mgustafsson1 @jochenkressin is this fixed?

**Comment by jochenkressin** [comment]
Fixed with the new config structure in SG7.
