### ISSUE TITLE
Link to edit role's index-level permission does not work when regex is used

### ISSUE THREAD

**Issue by occho** [floragunncom/search-guard-kibana-plugin#111]
## Issue

In the view to edit roles, the link to edit role's index-level permission does not work when regex is used for the index pattern.

![2018-07-26 11 33 09](https://user-images.githubusercontent.com/1100890/43238137-dbd1c1e4-90c7-11e8-88f2-314d9b8aeb2c.png)

The text `/\S*/` is linked to `http://HOST:5601/app/searchguard-configuration#/roles/edit/0-test/%2F%5CS*%2F`.

When clicking the link with Chrome, it jumps to `http://HOST:5601/app/searchguard-configuration#/roles/edit/0-test//%5CS*/?_g=()`.
Then, nothing is shown. Neither errors and warnings found from chrome console.

![2018-07-26 11 39 25](https://user-images.githubusercontent.com/1100890/43238319-b666994c-90c8-11e8-845b-7763f9c3e85b.png)

## Versions

The versions I've experienced the issue with:
Elasticserch version: 6.3.1
SeachGuard ES plugin version: 6-6.3.1-22.3
Kibana version: 6.3.1
SearchGuard Kibana plugin version: 6.3.1-14-beta-1

**Comment by floragunncom** [comment]
This was fixed in the latest v14 release of the plugin
