### ISSUE TITLE
Kibana 6.3.1 beta 1 - sessions timing out even with auto-refresh enabled

### ISSUE THREAD

**Issue by ceeeekay** [floragunncom/search-guard-kibana-plugin#114]
Since upgrading to 6.3.1 and installing Kibana plugin 6.3.1-14-beta-1, any dashboards left sitting with auto-refresh enabled will expire their session and display an "Unauthorised" banner after one hour.

This was not happening with 6.3.0.

Obviously it's not a good situation for unattended dashboards, as they need regular intervention.

Kibana / ES 6.3.1
Ubuntu 16.04
Firefox 61.0.1

**Comment by floragunncom** [comment]
This was fixed in the lates v14 release of the plugin
