### ISSUE TITLE
Tenant not removed on logout/login

### ISSUE THREAD

**Issue by jochenkressin** [floragunncom/search-guard-kibana-plugin#12]
ES/KI/SG 5.2.2-mt-beta2

Steps to reproduce:
1. Log in to Kibana with a user that has access to "tenant_a"
2. Select "tenant_a"
3. Log out, and log in with another use w/o access to "tenant_a"

Result:
"tenat_a" is still selected, leading to an empty dashboard/visualization view due to security exceptions

Expected:
Global tenant is selected by default on login

Solution:
When performing a login or logout operation, clear the currently selected tenant cookie/storage.

**Comment by floragunncom** [comment]
already implemented in logout route via reply({}).unstate('searchguard_tenant');
