### ISSUE TITLE
Typo in build.sh ? 

### ISSUE THREAD

**Issue by sehdorn** [floragunncom/search-guard-kibana-plugin#122]
Hey guys,

i am trying to package the plugin and make the build run, and I stumbled upon this:
https://github.com/floragunncom/search-guard-kibana-plugin/blob/85e900ee3855f6ae0a6043a1d3fcf6b70ea5d7d1/build.sh#L3
Could it be, that 

> PLUGIN_VERSION

 needs to be assigned to $2 ? Otherwise I do not really see any assignment of $2, so what it is about?
Also, any further hints about building the plugin would be really appreciated. Why is the build-script checking out the complete Kibana-Repo? And why is there no reference to mvn (mvn build out of the box not running, btw) in the build.sh?

**Comment by floragunncom** [comment]
The PLUGIN_VERSION is indeed a leftover and can be removed. $2 is used just one line below:

`PLUGIN_NAME="searchguard-kibana-$1-$2"`

Will correct that glitch in the script.

**Comment by jochenkressin** [comment]
Corrected in Kibana plugin v15.
