### ISSUE TITLE
Usecase: Using kibana plugin as standalone

### ISSUE THREAD

**Issue by bienensenf** [floragunncom/search-guard-kibana-plugin#123]
Hello,

I would like to use this plugin as standalone so independent from the elasticsearch plugin. I would be pretty free in terms of authentication type. Is this possible? A workaround would also be okay like writing files and pretending the plugin was installed.

Thank you very much

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard or, if you are a paying customer, contact our support.

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations or the issue will likely be closed as invalid:

* Search Guard and Elasticsearch version
* Kibana plugin version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug
* sg_*.yml config files
* kibana.yml file
* elasticsearch.yml file

These informations are optional but are very valuable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
