### ISSUE TITLE
Kibana Plugin not working on ES 6.3.2 installation

### ISSUE THREAD

**Issue by janniten** [floragunncom/search-guard-kibana-plugin#127]
Hi, I'm trying to setup SearchGuard on a ELK Stack 6.3.2.
I have problems with the kibana plugin.
Following the instructions in the "Demo Installer" documentation, when "Testing the Kibana installation" I get this error:

X-Pack Security needs to be disabled for Search Guard to work properly. Please set 'xpack.security.enabled' to false in your kibana.yml

I haven't install the X-Pack, but reading the ES documentation I've noticed that X-PAck is installed by default, so I set up the xpack.security.enabled to false in kibana.yml, but still working.

Inspecting the kibana process it seems that it is all the time restarting (pid is changing every 15s).

In addition I coudn´t find any relevant log with more information...

I'm lost... Any help would be appreciated..

Regards
Ana

**Comment by janniten** [comment]
Hi
It is a permission problem... If I run kibana as root it worked.
So, it is some permission wrong in my searchguard installation.
I performed the plugin installation as root, With which user should I perform the installation or which permission should the searchguard folder/archives have?
Thank you
Regards
Ana

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard or, if you are a paying customer, contact our support.

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations or the issue will likely be closed as invalid:

* Search Guard and Elasticsearch version
* Kibana plugin version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug
* sg_*.yml config files
* kibana.yml file
* elasticsearch.yml file

These informations are optional but are very valuable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
