### ISSUE TITLE
Double basic auth window

### ISSUE THREAD

**Issue by fe7ch** [floragunncom/search-guard-kibana-plugin#155]
Elasticsearch version: 6.5.1
Search Guard version: 23.2
Kibana plugin version: 16
JVM version: Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_191/25.191-b12
OS version: Linux/4.4.0-116-lowlatency/amd64

I was following the docs https://docs.search-guard.com/latest/kibana-authentication-http-basic and end up with the following lines in kibana.yml:

```
elasticsearch.requestHeadersWhitelist: [ "Authorization", "sgtenant" ]

xpack.security.enabled: false
searchguard.allow_client_certificates: true

searchguard.auth.type: "basicauth"
searchguard.cookie.secure: true
searchguard.cookie.password: <censored>
searchguard.cookie.ttl: 86400000 # 1000 * 60 * 60 * 24
searchguard.session.ttl: 86400000 # 1000 * 60 * 60 * 24
searchguard.session.keepalive: true
searchguard.basicauth.forbidden_usernames: ["kibanaserver", "logstash"]
```

When I try to login into kibana, I have to type credentials into search guard's login page & later in the browser's pop up window.

I'm aware of the https://github.com/floragunncom/search-guard/issues/400 issue, however, even if I add "sg_tenant" to the elasticsearch.requestHeadersWhitelist, it doesn't change anything. 

By the way, which name is the correct - "sg_tenant" specified in https://github.com/floragunncom/search-guard/issues/400 or "sgtenant" specified in documentation?

**Comment by jochenkressin** [comment]
Please have a look at the upgrade instructions:

https://docs.search-guard.com/latest/upgrading-560

You need to disable Spaces for the moment, a fix for this is on the way!

**Comment by fe7ch** [comment]
Thanks. Indeed, the `xpack.spaces.enabled: false` fixed the issue.

However, I wasn't upgrading to 5.6+, at the time when I installed search-guard for the first time I was already using es 6.5.1 and I haven't seen requirement for the `xpack.spaces.enabled` in the installation instructions.

**Comment by floragunncom** [comment]
We will add this also to the installation instructions, thx a lot.

**Comment by fe7ch** [comment]
>By the way, which name is the correct - "sg_tenant" specified in floragunncom/search-guard#400 or "sgtenant" specified in documentation?

@floragunncom Could you please also comment on this one?

**Comment by floragunncom** [comment]
It's `sgtenant`

**Comment by fe7ch** [comment]
Thanks!
