### ISSUE TITLE
Version information in documentation of Kibana plugin accountinfo feature missleading

### ISSUE THREAD

**Issue by breml** [floragunncom/search-guard-kibana-plugin#162]
The current version of the documentation of the [`searchguard.accountinfo.enabled` feature](https://docs.search-guard.com/latest/kibana-account-overview) states the version required is *6.x-24* which refers to the version of the Searchguard plugin for Elasticsearch and not for the Kibana plugin (there is no version 24 for the Kibana plugin). As far as I can tell, the minimum version of the Kibana plugin is *6.x-16* for this feature to work.

I checked out the documentation repo (issue tracker is disabled there) but I was not able to figure out how to fix this.

**Comment by floragunncom** [comment]
@mgustafsson1 @jochenkressin can you have a look?

**Comment by floragunncom** [comment]
Yes it's [Kibana >= v16](https://github.com/floragunncom/search-guard-kibana-plugin/commit/9240fd624487f23546dfefe52d98a6986df6b6ae#diff-c91a79cd32b846822f6bc849f65c744f).

@jochenkressin docs are currently versioned by sg version, not kibana version. Lets think about this.

**Comment by jochenkressin** [comment]
I totally agree it is confusing. We decided on a different versioning schema for ES and KI in order to be able to release (bugfix) versions for ES and KI independently. However, more often than not fixes or features require minimum versions for ES *and* KI. We will very likely change the versioning schema for SG7 to avoid this confusion.

**Comment by floragunncom** [comment]
We have this overview already, maybe it helps until then: https://docs.search-guard.com/latest/search-guard-versions

**Comment by jochenkressin** [comment]
Aligned the version for SG and KI plugins with SG7
