### ISSUE TITLE
Provide Version Information of search-guard-kibana-plugin in UI

### ISSUE THREAD

**Issue by breml** [floragunncom/search-guard-kibana-plugin#164]
As mentioned/asked in https://github.com/floragunncom/search-guard-module-kibana-multitenancy/issues/13#issuecomment-396205117, it seams, that there is currently now way to get the version number of the `search-guard-kibana-plugin` installed in Kibana. The *Search Guard System Status* page in Kibana only shows the version inforation of the Search-Guard modules/plugins installed with Elasticsearch.

**Comment by floragunncom** [comment]
@mgustafsson1 @jochenkressin can you have a look? Is it the same as ITT-1728?

**Comment by jochenkressin** [comment]
The plugin version is now displayed on the Search Guard system info page and in the accounts info page.
