### ISSUE TITLE
Read/Open saved search (Discover View) not available with read-only tenant permission

### ISSUE THREAD

**Issue by breml** [floragunncom/search-guard-kibana-plugin#165]
With multi tenancy enabled and a user with read-only permission for the selected tenant in Kibana, the user is not able to read/open saved searches in the Discover view of Kibana. The whole menu-bar is not visible for the user.

This is the same for the Visualize and Dashboard Views, but there it is less severe, because Kibana by default offers a list of the available Visualizations/Dashboards when selecting this view.

**Comment by floragunncom** [comment]
@mgustafsson1 @jochenkressin can you have a look?

**Comment by jochenkressin** [comment]
This should be fixed with this PR: https://github.com/floragunncom/search-guard-kibana-plugin/pull/149. The PR is already merged in v17 of the plugin, the release to be announced. @breml which version are you currently using?

**Comment by breml** [comment]
As we are currently using version 6.2.4 of the Elastic Stack, version 15 of the Search-Guard Kibana plugin is the most recent version available. There are plans to update to a more recent version of the Elastic Stack, which would make available the more recent versions of the Kibana plugin, but currently we are not there yet.
