### ISSUE TITLE
Add sanity checks to plugin

### ISSUE THREAD

**Issue by jochenkressin** [floragunncom/search-guard-kibana-plugin#17]
In order for MT to work, a couple of prerequisites have to be met:

* kibana index name must be configured in KI and ES
* kibana server user must be configured in KI and ES
* sg_tenant header must be whitelisted

Add checks against (new) MT endpoint:

```
{
  "kibana_mt_available": true,
  "kibana_index": ".kibana",
  "kibana_server_user": "kibanaserver",
  "kibana_index_readonly": false
}
```

**Comment by floragunncom** [comment]
Fixed with beta-3
