### ISSUE TITLE
5.x version JWT and `sg_tenant` parameter with multi-tenancy enabled

### ISSUE THREAD

**Issue by jacobhummer** [floragunncom/search-guard-kibana-plugin#174]
I'm on the latest 5.x version (`v5.6.15-7` specifically) of this plugin and Kibana fails to load (error from Kibana included below) when leveraging both JWT as URL parameter and having multi-tenancy enabled with the use of the `sg_tenant` parameter as well.

Basically the `authinfo` call [here](https://github.com/floragunncom/search-guard-kibana-plugin/blob/v5.6.15-7/lib/multitenancy/headers.js#L36) fails due to MT being loaded/required before JWT in the `index.js` file so the `Authorization` header is not included prior to this call.  I dug through the code and found the fix so I'm just curious if we could get this applied to a new 5.x version? 

FIX: https://github.com/floragunncom/search-guard-kibana-plugin/commit/21a746df92e9b6cf38addfa0ab07d03dfd29701b#diff-168726dbe96b3ce427e7fedce31bb0bc

**Error From Kibana:**
```
Feb 26 18:39:56 navigator-dev kibana[29691]: {"type":"error","@timestamp":"2019-02-26T18:39:56Z","tags":["warning","process"],"pid":29691,"level":"error","error":{"message":"Unhandled promise rejection (rejection id: 1): AuthenticationError","name":"UnhandledPromiseRejectionWarning","stack":"AuthenticationError\n    at AuthenticationError (/usr/share/kibana/plugins/searchguard/lib/auth/authentication_error.js:20:5)\n    at /usr/share/kibana/plugins/searchguard/lib/backend/searchguard.js:62:23\n    at throw (native)\n    at step (/usr/share/kibana/plugins/searchguard/lib/backend/searchguard.js:29:191)\n    at /usr/share/kibana/plugins/searchguard/lib/backend/searchguard.js:29:402"},"message":"Unhandled promise rejection (rejection id: 1): AuthenticationError"}
```

**Comment by floragunncom** [comment]
@jochenkressin @mgustafsson1 can you have a look?

**Comment by mgustafsson1** [comment]
@jacobhummer I think your analysis is right on point. I'll look into this! Thanks!

**Comment by jacobhummer** [comment]
Awesome thank you! Happy to provide anymore info if needed.

**Comment by jacobhummer** [comment]
I was able to confirm swapping the order to require JWT first before Multitenancy artifacts in the `index.js` file resolves my issue.  Screenshot of diff:
![image](https://user-images.githubusercontent.com/4721891/54150057-f78d3180-440d-11e9-8aed-0c5f244e8b69.png)

I just tested this locally by updating my `index.js` file directly though. Would it help if I put together a PR for this against the latest `es-5.6.15` branch?

**Comment by mgustafsson1** [comment]
@jacobhummer If you have the time, a PR would be great!
If you don't, I'll do my best to get this implemented and tested before the next release though!

**Comment by jacobhummer** [comment]
thank you @mgustafsson1 much appreciated!

**Comment by mgustafsson1** [comment]
@jochenkressin I believe this was already released and we can close this?

**Comment by jochenkressin** [comment]
Yes, this has been released
