### ISSUE TITLE
Broken link for 6.4.0-18.1

### ISSUE THREAD

**Issue by adrianmester** [floragunncom/search-guard-kibana-plugin#182]
https://docs.search-guard.com/latest/search-guard-versions

The link on this page is currently broken:

https://oss.sonatype.org/service/local/repositories/releases/content/com/floragunn/search-guard-kibana-plugin/6.7.0-18.1/search-guard-kibana-plugin-6.7.0-18.1.zip

I assume there was an issue with the automated build?

**Comment by floragunncom** [comment]
Already fixed, correct link is https://oss.sonatype.org/service/local/repositories/releases/content/com/floragunn/search-guard-kibana-plugin/6.7.0-18.2/search-guard-kibana-plugin-6.7.0-18.2.zip (and there will be a 18.3 release shortly)
