### ISSUE TITLE
Kibana plugin doesn't seem to be linked with the conf files

### ISSUE THREAD

**Issue by Amarquier** [floragunncom/search-guard-kibana-plugin#183]
Hi,
I'm using the demo version and the last version of the plugin.

I don't know if this is a normal behavior or an issue but when I add a new user through kibana UI it is not written in the conf file (sg_internal_users.yml for this example). This is the case for both directions and for other conf files too

Did I missed something in the installation guide ? If no, what's the point of not having them synchronized ?

Thanks in advance.

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://forum.search-guard.com or, if you are a paying customer, contact our support.

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations or the issue will likely be closed as invalid:

* Search Guard and Elasticsearch version
* Kibana plugin version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug
* sg_*.yml config files
* kibana.yml file
* elasticsearch.yml file

These informations are optional but are very valuable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
