### ISSUE TITLE
what permission should I config when below error turns out

### ISSUE THREAD

**Issue by Zuckonit** [floragunncom/search-guard-kibana-plugin#20]
```
no permissions for indices:data/read/field_stats ::
{
    "path": "/xyz/_field_stats",
    "query": {
        "fields": "*",
        "allow_no_indices": false
    },
    "statusCode": 403,
    "response": "{\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"no permissions for indices:data/read/field_stats\"}],\"type\":\"security_exception\",\"reason\":\"no permissions for indices:data/read/field_stats\"},\"status\":403}"
}
```

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
