### ISSUE TITLE
can't start kibana with custom server basePath

### ISSUE THREAD

**Issue by becemwniss** [floragunncom/search-guard-kibana-plugin#22]
I set the server basePath in kibana.yml file : "server.basePath: /reporting" and i have used HAProxy to remove the server basePath but when trying to access [http://IP/reporting](http://IP/reporting) this redirect me to [http://IP/reporting/searchguard/login](http://IP/reporting/searchguard/login) (this is the expected behavior) but i see only a blank page.
so i was wondering is there any other configuration should i do ?

Thanks

**Comment by jochenkressin** [comment]
Which version of

* Elasticsearch
* Kibana
* Search Guard

are you using?

Can you please also post the kibana logfile?

**Comment by bwniss** [comment]
- Elasticsearch : 5.2.2
- kibana :5.2.2
- Searchguard: 5.2.2-11
logs:
`{"type":"log","@timestamp":"2017-05-03T11:13:21Z","tags":["status","plugin:kibana@5.2.2","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-05-03T11:13:21Z","tags":["status","plugin:elasticsearch@5.2.2","info"],"pid":1,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-05-03T11:13:21Z","tags":["status","plugin:elasticsearch@5.2.2","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - Service Unavailable","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2017-05-03T11:13:21Z","tags":["status","plugin:console@5.2.2","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-05-03T11:13:22Z","tags":["status","plugin:searchguard@5.2.2","info"],"pid":1,"state":"yellow","message":"Status changed from uninitialized to yellow - Initialising Search Guard authentication plugin.","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-05-03T11:13:22Z","tags":["status","plugin:searchguard@5.2.2","info"],"pid":1,"state":"yellow","message":"Status changed from yellow to yellow - 'searchguard.cookie.secure' is set to false, cookies are transmitted over unsecure HTTP connection. Consider using HTTPS and set this key to 'true'","prevState":"yellow","prevMsg":"Initialising Search Guard authentication plugin."}
{"type":"log","@timestamp":"2017-05-03T11:13:22Z","tags":["status","plugin:searchguard@5.2.2","info"],"pid":1,"state":"yellow","message":"Status changed from yellow to yellow - Search Guard HTTP Basic Authentication enabled.","prevState":"yellow","prevMsg":"'searchguard.cookie.secure' is set to false, cookies are transmitted over unsecure HTTP connection. Consider using HTTPS and set this key to 'true'"}
{"type":"log","@timestamp":"2017-05-03T11:13:22Z","tags":["status","plugin:searchguard@5.2.2","info"],"pid":1,"state":"green","message":"Status changed from yellow to green - Search Guard plugin initialised.","prevState":"yellow","prevMsg":"Search Guard HTTP Basic Authentication enabled."}
{"type":"log","@timestamp":"2017-05-03T11:13:22Z","tags":["status","plugin:timelion@5.2.2","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-05-03T11:13:22Z","tags":["listening","info"],"pid":1,"message":"Server running at http://localhost:5601"}
{"type":"log","@timestamp":"2017-05-03T11:13:22Z","tags":["status","ui settings","error"],"pid":1,"state":"red","message":"Status changed from uninitialized to red - Elasticsearch plugin is red","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-05-03T14:55:24Z","tags":["status","plugin:elasticsearch@5.2.2","info"],"pid":1,"state":"yellow","message":"Status changed from red to yellow - No existing Kibana index found","prevState":"red","prevMsg":"Service Unavailable"}
{"type":"log","@timestamp":"2017-05-03T14:55:24Z","tags":["status","ui settings","info"],"pid":1,"state":"yellow","message":"Status changed from red to yellow - Elasticsearch plugin is yellow","prevState":"red","prevMsg":"Elasticsearch plugin is red"}
{"type":"log","@timestamp":"2017-05-03T14:55:24Z","tags":["status","plugin:elasticsearch@5.2.2","info"],"pid":1,"state":"green","message":"Status changed from yellow to green - Kibana index ready","prevState":"yellow","prevMsg":"No existing Kibana index found"}
{"type":"log","@timestamp":"2017-05-03T14:55:24Z","tags":["status","ui settings","info"],"pid":1,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Elasticsearch plugin is yellow"}`.
Thanks.

**Comment by jochenkressin** [comment]
So far we were not able to reproduce your issue. Could you please also provide your HAProxy configuration so we can replicate the problem? Thx!

**Comment by duramen** [comment]
I have a same problem,I config elasticsearch.url:"xxx.com:80"(nginx proxy es 9200 )  in kibana.yml.

> {"type":"error","@timestamp":"2017-04-18T06:52:24Z","tags":[],"pid":16929,"level":"error","message":"Internal Server Error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at async$ (/root/kibana-5.1.1-linux-x86_64/plugins/searchguard/lib/routes/routes.js:66:43)\n    at tryCatch (/root/kibana-5.1.1-linux-x86_64/node_modules/regenerator/runtime.js:61:40)\n    at GeneratorFunctionPrototype.invoke [as _invoke] (/root/kibana-5.1.1-linux-x86_64/node_modules/regenerator/runtime.js:328:22)\n    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/root/kibana-5.1.1-linux-x86_64/node_modules/regenerator/runtime.js:94:21)\n    at GeneratorFunctionPrototype.invoke (/root/kibana-5.1.1-linux-x86_64/node_modules/regenerator/runtime.js:136:37)\n    at bound (domain.js:280:14)\n    at GeneratorFunctionPrototype.runBound (domain.js:293:12)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"","query":{},"pathname":"/searchguard/api/v1/auth/login","path":"/searchguard/api/v1/auth/login","href":"/searchguard/api/v1/auth/login"}}
Debug: internal, implementation, error 
    Error: Internal Server Error
    at async$ (/root/kibana-5.1.1-linux-x86_64/plugins/searchguard/lib/routes/routes.js:66:43)
    at tryCatch (/root/kibana-5.1.1-linux-x86_64/node_modules/regenerator/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/root/kibana-5.1.1-linux-x86_64/node_modules/regenerator/runtime.js:328:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/root/kibana-5.1.1-linux-x86_64/node_modules/regenerator/runtime.js:94:21)
    at GeneratorFunctionPrototype.invoke (/root/kibana-5.1.1-linux-x86_64/node_modules/regenerator/runtime.js:136:37)
    at bound (domain.js:280:14)
    at GeneratorFunctionPrototype.runBound (domain.js:293:12)


but elasticsearch.url:"1.1.1.1:9200" is OK， and why？

**Comment by jochenkressin** [comment]
Like I said, we're not able to reproduce the behavior, it works fine with HAProxy in our test environment. If you do not provide more info, especially the HAProxy or nginx configuration, we're not able to help.

**Comment by duramen** [comment]
nginx config:

> location / {
            proxy_pass http://es;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

**Comment by jochenkressin** [comment]
That's not how base path in Kibana works, it has nothing to do with request forwarding to Elasticsearch.

Base path is for Kibana (not ES) instances running behind a proxy. Basically, Kibana adds the base path to all URLs, and the proxy is supposed to remove it before it hands the request down to Kibana.

https://github.com/elastic/kibana/issues/6665

"Enables you to specify a path to mount Kibana at if you are running behind
a proxy. The basePath value does not change the address that kibana listens
on, instead, your proxy is expected to remove the basePath value before
forwarding requests to Kibana. This setting cannot end in a slash (/)."

For example, if you set the base path to:

server.basePath: "/base"

This HAProxy configuration works fine:

```
frontend https-in
    bind *:8080
    mode http
    option forwardfor

    default_backend kibana

backend kibana
    mode http
    balance leastconn
    option forwardfor

    # redirect to /kibana if path is /
    acl has_path path_beg /base
    http-request redirect code 301 location /base unless has_path

    # remove /kibana from the beginning of the URI
    reqrep ^([^\ :]*)\ /base/(.*) \1\ /\2
    reqrep ^([^\ :]*)\ /base      \1\ /

    server kibana localhost:5601 
```

**Comment by duramen** [comment]
I am not config basePath，I config elasticsearch.url.......

**Comment by jochenkressin** [comment]
@duramen This issue is about using a basePath with Kibana, as the title says: "can't start kibana with custom server basePath". Please do not hijack issues, and only report bugs here.

If you have problems with Proxy configuration, please ask on out Google Groups:

**Comment by jochenkressin** [comment]
@becemwniss ping - please compare your HAProxy conf with the one I've posted.

**Comment by floragunncom** [comment]
No response, cannot reproduce, working HA config provided, will close the issue.

**Comment by duramen** [comment]
@jochenkressin 
I am sorry。
I review the js code and look network request，discover：

> 1.1.1.1 - - [16/May/2017:10:37:44 +0800] "GET _searchguard/authinfo HTTP/1.1" 400 594 "-" "-" "-" 0.000 "-" "-"

so I use `grep -r _searchguard/authinfo *` in kibana directory.

> plugins/searchguard/lib/backend/searchguard_plugin.js:      fmt: '_searchguard/authinfo'

modify

> fmt: '/_searchguard/authinfo'

everything is ok.

Thanks.

**Comment by willouuu** [comment]
Hi 
I have same error, after login, redirect is http://monip/ instead of http://monip/kibana/ but the session is created

proxypass apache : 
```
<Location "/kibana/">
  ProxyPass "http://localhost:5601/"
  ProxyPassReverse "http://localhost:5601/kibana/"
</Location>
```

kibana.yml
`server.basePath: "/kibana"`


kibana.log : 

> {"type":"response","@timestamp":"2018-03-26T09:35:41Z","tags":[],"pid":16694,"method":"post","statusCode":200,"req":{"url":"/api/v1/auth/login","method":"post","headers":{"host":"localhost:5601","accept":"application/json, text/plain, */*","origin":"http://monip","kbn-version":"6.2.2","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36","content-type":"application/json;charset=UTF-8","dnt":"1","referer":"http://monip/kibana/login","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9,fr-FR;q=0.8,fr;q=0.7","x-forwarded-for":"myhostclient","x-forwarded-host":"monip","x-forwarded-server":"elasticstack.irit.fr","connection":"Keep-Alive","content-length":"39"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://monip/kibana/login"},"res":{"statusCode":200,"responseTime":11,"contentLength":9},"message":"POST /api/v1/auth/login 200 11ms - 9.0B"} 
> {"type":"response","@timestamp":"2018-03-26T09:35:41Z","tags":[],"pid":16694,"method":"get","statusCode":200,"req":{"url":"/api/v1/restapiinfo","method":"get","headers":{"host":"localhost:5601","accept":"application/json, text/plain, */*","kbn-version":"6.2.2","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36","dnt":"1","referer":"http://monip/kibana/login","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9,fr-FR;q=0.8,fr;q=0.7","x-forwarded-for":"myhostclient","x-forwarded-host":"monip","x-forwarded-server":"elasticstack.irit.fr","connection":"Keep-Alive"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://monip/kibana/login"},"res":{"statusCode":200,"responseTime":41,"contentLength":9},"message":"GET /api/v1/restapiinfo 200 41ms - 9.0B"}
