### ISSUE TITLE
Merge Proxy Auth in all versions 

### ISSUE THREAD

**Issue by jochenkressin** [floragunncom/search-guard-kibana-plugin#23]
We have implemented support for Proxy Auth in the plugin by copying all configured and whitelisted headers to the request.

Merge these changes to the next official (v3) release of the plugin.

Keep in mind:

- If no header is whitelisted, authorisation is the default
- If this header is not present (in case of proxy auth), Kibana takes the kibana server user as default
- thus, the SSO/Proxy auth must come first in the config!

Check also whether we handle the default case (no header whitelisted) correctly.

**Comment by yasvanth** [comment]
@jochenkressin Could we have a look at example kibana.yml ?

**Comment by jochenkressin** [comment]
Actually there's nothing to configure. You only need to whitelist the authentication headers in kibana.yml, as described in the docs. There's a proxy section in the docs here: https://github.com/floragunncom/search-guard-docs/blob/master/kibana.md

**Comment by jochenkressin** [comment]
Fixed with v3 release.
