### ISSUE TITLE
Kibana Dashboard ReadOnly Mode along with Uptime Dashboard

### ISSUE THREAD

**Issue by riteshsoni10** [floragunncom/search-guard-kibana-plugin#274]
Is there any way to configure kibana dashboard readonly mode along with uptime dashboard.

OS: Centos 7.6
ElasticSearch : 7.0.0
ElasticSearch Plugin Version: 7.0.0.35
Kibana: 7.0.0
Kibana SearchGuard Plugin Version: 7.0.0.35

**Comment by riteshsoni10** [comment]
@floragunncom

**Comment by jochenkressin** [comment]
Sorry for the late reply. At the moment, no, this is not possible. However, we're working on improving this and plan to have something ready this month which will give you better control over the Kibana apps.
