### ISSUE TITLE
twice kibana authentication issue

### ISSUE THREAD

**Issue by vsevolodk** [floragunncom/search-guard-kibana-plugin#29]
Hi.
Please, give more info about [#298](https://github.com/floragunncom/search-guard/issues/298).
@floragunncom wrote this [comment](https://github.com/floragunncom/search-guard/issues/298#issuecomment-308771157).
Could you specify link on the original kibana issue?
Am I right that only the kibana issue pushed your team to write this kibana plugin?
May be better fix it on the kibana side?

**Comment by jochenkressin** [comment]
Yes and no. Besides the session management, the plugin also provides multi-tenancy, so it's required to support all features of Search Guard anyways. Patching Kibana is not an option, due to the fact that every Kibana feature is a separate, encapsulated plugin. May I ask what's the background of your question?

**Comment by vsevolodk** [comment]
Thank you for the answer.
I have my own authentication engine for elastic search, and I have also faced with twice kibana authentication issue.
So, I am searching for its rootcause and I hope that it's a well-known (familiar) issue.
Do you have a link or any information on kibana issue?

**Comment by jochenkressin** [comment]
It's not an issue or bug, it's just the way Kibana is designed. Each feature, like Dashboard, Timelion or Sense is a separate plugin which may or may not use a dedicated connection to ES. If you open Kibana, the default app is loaded, and depending on your ES backend, a login prompt is displayed. The credentials are reused for this connection. You switch to another app which uses a different connection, and are prompted again. Besides a plugin that handles the session management, IMHO there's not other way around this.

**Comment by vsevolodk** [comment]
@jochenkressin thank you very much.
I found the next [information](https://github.com/elastic/kibana/issues/1464#issuecomment-55716739). Does it work only for one dedicated ES connection?

**Comment by jochenkressin** [comment]
I think this is more a Kibana than a Search Guard question, so it's better to ask this on the ES/KI forums.
