### ISSUE TITLE
old release

### ISSUE THREAD

**Issue by holmbergth** [floragunncom/search-guard-kibana-plugin#30]
Hi, i'm looking for an  elder release
more specific the 5.0.0-x for the kibana plugin
is there another repo for this release

**Comment by floragunncom** [comment]
no, SG Kibana Plugin is not available for Kibana 5.0.0 and 5.0.1 (and was never) because of Bugs in Kibana. Pls update to at least Kibana 5.0.2.

**Comment by holmbergth** [comment]
thank you
