### ISSUE TITLE
Kibana Status Endpoint not reachable

### ISSUE THREAD

**Issue by jochenkressin** [floragunncom/search-guard-kibana-plugin#31]
If the Kibana plugin is enabled, the status endpoint is not reachable anymore.

See: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/search-guard/z7NiBqCRm50

We should check if the can exclude this endpoint from the authentication checks, if it does not call Elasticsearch in return. Need to check that.

**Comment by floragunncom** [comment]
Fixed with latest v4 snapshot, will close issue upon official release

**Comment by floragunncom** [comment]
fixed with v4 released today
