### ISSUE TITLE
Endless loading when using JWT and multitenancy in some cases

### ISSUE THREAD

**Issue by jochenkressin** [floragunncom/search-guard-kibana-plugin#33]
If multitenancy is enabled and SSO is used (JWT for example), the onPostAuth interceptor in multitenancy/headers.js is called for each authenticated request.

Sometimes these calls do not contain any authentication information, which leads to an exception when backend.authinfo() is called.

Figure out where these calls stem from, check why the onPostAuth interceptor is called at all, and omit the backend.authinfo() if we don't have any auth information.

**Comment by floragunncom** [comment]
fixed with v4 released today
