### ISSUE TITLE
Custom next url after login

### ISSUE THREAD

**Issue by iFedix** [floragunncom/search-guard-kibana-plugin#36]
Hi! I have a problem.. i would like to be able to redirect a user to a custom page based on the user name.
In my case i just want that after i log in with a user named samsungtv, the searchguard login redirects me in a custom kibana view i created (i have the url). What is a smart way to do this? Is there a way to redirect a user based on his user name? Thank you!

**Comment by jochenkressin** [comment]
Please use GitHub for reporting bugs only, for questions there's the Search Guard Google Groups forum: https://groups.google.com/forum/#!forum/search-guard

As to your question, have a look at public/apps/login_controller.js

In the response handler of the login method you have the username available, and can set a custom next url based on the user's name.

**Comment by iFedix** [comment]
@jochenkressin ok thx! however that is what I tried.. but how to reload that file? I tried to restart nginx service and kibana, cleared sites cache but nothing changed (I tried also to modify the login error message just to see if that will change but nothing happened). Thank you!

**Comment by jochenkressin** [comment]
Maybe you hit the caching issue described here: https://github.com/floragunncom/search-guard/issues/345

**Comment by iFedix** [comment]
Yes probably, i have xpack installed too! What is the snapshot version of the kibana search guard plugin to solve also the xpack welcome screen? Should I just upgrade to that version following mat1010 advise with my modifications in login_controller.js? Thank you.

**Comment by jochenkressin** [comment]
Yes, if you're running 5.4.0 or 5.4.2 then you can just use one of the snapshots referenced in floragunncom/search-guard#345. The official release will take another 2 weeks or so, since we're integrating other features and fixed as well.

**Comment by iFedix** [comment]
Does it also work with 5.4.1 version? Thank you!

**Comment by jochenkressin** [comment]
No, Kibana requires the versions to match. But you could try to simply adjust the version number in package.json. At the moment we will not prepare snapshot versions, since we're in the process of merging for the next official release. But give it a try, I think there are no fundamental differences between, say, 5.4.0 and 5.4.1

**Comment by iFedix** [comment]
@jochenkressin Solved! Removed prior version and adapted 5.4.2 snapshot to work with my 5.4.1. Changed some code in login_controller.js to support an external url and it worked well. Thank you for help!
