### ISSUE TITLE
Support x-pack monitoring together with search-guard

### ISSUE THREAD

**Issue by romankor** [floragunncom/search-guard-kibana-plugin#38]
I am trying to start kibana together with x-pack plugin and search-guard plugin installed.
Of course i have `xpack.security.enabled: false`

The startup fails : 
`Unhandled rejection Error: Plugin hapi-auth-cookie already registered in: http://0.0.0.0:5601`
`log   [23:01:29.404] [fatal] Error: cluster 'security' already exists`

Anyhow can Imake them both work together ? I would like to have the monitoring feature working from xpack that is provided with its basic license.

**Comment by floragunncom** [comment]
You need to disable all x-pack components but monitoring. 


elasticsearch.yml/kibana.yml
<pre>
xpack.monitoring.enabled: true
xpack.graph.enabled: false
xpack.ml.enabled: false
xpack.security.enabled: false
xpack.watcher.enabled: false
</pre>

See https://github.com/floragunncom/search-guard-docs/blob/master/monitoring.md for details.
