### ISSUE TITLE
Errors at login page show password

### ISSUE THREAD

**Issue by zargex** [floragunncom/search-guard-kibana-plugin#39]
If elasticsearch is down, search-guard page shows a 500 error code but with the following information:

> 
> {
> 	"data": {
> 		"statusCode": 500,
> 		"error": "Internal Server Error",
> 		"message": "An internal server error occurred"
> 	},
> 	"status": 500,
> 	"config": {
> 		"method": "POST",
> 		"transformRequest": [null],
> 		"transformResponse": [null],
> 		"url": "/api/v1/auth/login",
> 		"data": {
> 			"username": "USER",
> 			"password": "PASSWORD"
> 		},
> 		"headers": {
> 			"Accept": "application/json, text/plain, */*",
> 			"Content-Type": "application/json;charset=utf-8",
> 			"kbn-version": "5.5.0"
> 		}
> 	},
> 	"statusText": "Internal Server Error"
> }

Although that info is very useful, I think the username and password shouldn't show in plain text.

**Comment by floragunncom** [comment]
Showing the password is of course not intended. We will fix immediately, thanks for reporting!

**Comment by floragunncom** [comment]
Fixed with v4 released today
