### ISSUE TITLE
Add support for Duo 2fa integration

### ISSUE THREAD

**Issue by packetrevolt** [floragunncom/search-guard-kibana-plugin#40]
Would it be possible to add support for Duo 2fa into the Kibana login plugin?
https://duo.com/docs/authapi

**Comment by floragunncom** [comment]
This is not planned so far but we are glad to accept a PR for that.

**Comment by jdeplato** [comment]
Second @packetrevolt  - Need to implement some type of multi-factor auth.

**Comment by floragunncom** [comment]
Why do you not use SG proxy or JWT authentication and let nginx do the MFA work?

**Comment by fouts-bnet** [comment]
@jdeplato we've completed this using the LDAP Duo Proxy, the downside is the timeout is too short.
https://github.com/floragunncom/search-guard-kibana-plugin/issues/68

**Comment by floragunncom** [comment]
We will fix the timeout issue with the upcoming release

**Comment by jochenkressin** [comment]
Timeout is now configurable in [Search Guard v21](http://docs.search-guard.com/latest/changelog-6-x-21), released today
