### ISSUE TITLE
X-Pack monitoring broken in 5.6.3

### ISSUE THREAD

**Issue by jochenkressin** [floragunncom/search-guard-kibana-plugin#43]
The code for the X-Pack monitoring has changed and now loads a shield client regardless whether the Shield plugin is enabled at all or not.

This conflicts with the "security" cluster name in the Search Guard plugin, leading to:

`log   [13:16:52.964] [error][reporting] Error: cluster 'security' already exists`

on startup. Kibana refuses to start, plugins are red.

**Comment by yahel2410** [comment]
Has it been resolved?

**Comment by shortsteps** [comment]
It seems to happen in Kibana & SG 5.5.2 too.
Any help?

**Comment by druidushka** [comment]
@shortsteps I confirm. 
Kibana 5.5.2 with sg and xpack plugins has the same issue.

**Comment by jochenkressin** [comment]
Fixed with v5 for Kibana 5.6.x and 6.x

**Comment by druidushka** [comment]
@jochenkressin 
Is there any chance to have the fix for 5.5.x version?

**Comment by jochenkressin** [comment]
@druidushka we will backport the fix to the last supported 5.5.x version which according to our EOL policy is 5.5.3. Will be released this week.

**Comment by druidushka** [comment]
@jochenkressin 
Thanks,
But I fixed the problem, I just checked last commits to the 5.6.x branch and made the same things with 5.5.2. Now Kibana works perfectly with installed searchguard and x-pack plugins.

@shortsteps JFYI

**Comment by shortsteps** [comment]
@druidushka thanks a lot for the information, I'll try that.
Maybe you can open a pull request to help future search.

**Comment by chopchop505** [comment]
I'm now seeing this error with xpack.reporting enabled in 6.6.
Can you confirm search guard works with xpack reporting?

**Comment by CraightonH** [comment]
I had the same issue as above, but then got monitoring to work after adding the following lines to my `kibana.yml` file:
`
xpack.monitoring.enabled: true
xpack.security.enabled: false
xpack.spaces.enabled: false
xpack.graph.enabled: false
xpack.ml.enabled: false
xpack.apm.enabled: false
xpack.reporting.enabled: false
`
I think it was the reporting plugin that finally did that trick, but I haven't confirmed that with certainty.
