### ISSUE TITLE
"sg_tenant" header won't be passed to ES nodes by nginx

### ISSUE THREAD

**Issue by desp0916** [floragunncom/search-guard-kibana-plugin#44]
While running Elasticsearch and Search Guard behind nginx (as a loadbalancer), this plugin doesn't work properly if private tenant or multitenant is enabled.

After trying and surveying for almost one week, I finally found the root cause: "**sg_tenant**" header won't be passed by nginx because it contains a underscore and is marked as invalid by nginx. Please refer to this [serverfault Q&A](https://serverfault.com/questions/586970/nginx-is-not-forwarding-a-header-value-when-using-proxy-pass). The workaround is to set the following in nginx.conf:

> underscores_in_headers on;

However, I think the best way is to not use any **underscore** in header name.

**Comment by floragunncom** [comment]
Good catch, thx. We will think about a solution for SG6 and update the docs.

**Comment by floragunncom** [comment]
This has been fixed with SG6, the tenant header has been switched to "sgtenant" in both the Kibana plugin and the multi tenancy module. Thanks for reporting this!
