### ISSUE TITLE
Can't import dashboard when multitenancy is enabled

### ISSUE THREAD

**Issue by floragunncom** [floragunncom/search-guard-kibana-plugin#45]
Track https://github.com/floragunncom/search-guard-module-kibana-multitenancy/issues/12

**Comment by jochenkressin** [comment]
Fixed with v10 of the [Kibana](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.floragunn%22%20AND%20a%3A%22search-guard-kibana-plugin%22) plugin, released today.
