### ISSUE TITLE
Search Guard GUI not showing in kibana

### ISSUE THREAD

**Issue by EamonHetherton** [floragunncom/search-guard-kibana-plugin#46]
Hi, I have just installed "search-guard-kibana-plugin-6.0.0-6.beta1.zip" and I am not seeing the menu option for SearchGuard in the kibana interface.

I am running kibana version 6.0.0

```
mkdir /tmp/kibana
curl -o "/tmp/kibana/search-guard-kibana-plugin-6.0.0-6.beta1.zip" "https://search.maven.org/remotecontent?filepath=com/floragunn/search-guard-kibana-plugin/6.0.0-6.beta1/search-guard-kibana-plugin-6.0.0-6.beta1.zip" -L
/usr/share/kibana/bin/kibana-plugin install file:///tmp/kibana/search-guard-kibana-plugin-6.0.0-6.beta1.zip

service kibana stop
/usr/share/kibana/bin/kibana-plugin remove searchguard
service kibana start
#wait 5 minutes
service kibana stop
/usr/share/kibana/bin/kibana-plugin install file:///tmp/kibana/search-guard-kibana-plugin-6.0.0-6.beta1.zip
service kibana start
```
It's loading searchguard as I have to log in (and as you can see there is the Logout option). I am logging in as the demo 'admin/admin' account.

is there a setting i need in kibana.yml?

![image](https://user-images.githubusercontent.com/449015/33291182-b4080e58-d410-11e7-972e-1276fcf6febf.png)

**Comment by floragunncom** [comment]
Not in kibana.yml, but you need to configure access to the REST API (which the config GUI uses under the hood) for the logged in user:

In elasticsearch.yml, configure it like:

searchguard.restapi.roles_enabled: ["sg_all_access", ...]

More information: http://docs.search-guard.com/latest/kibana-configuration-search-guard

In short, when you log in, we check whether the current user has access to the REST API or not. If the user does not have any access permitted, the config GUI is disabled.

Did you set the roles_enabled in elasticsearch.yml, and does your currently logged in user belong to the configured role(s)?

**Comment by EamonHetherton** [comment]
That's done it.  for some reason I only had that setting on one of the three nodes.  I added it to the other two nodes and did a full cluster restart and it's there now. 

Thanks for the prompt response.

**Comment by HansaTheDeveloper** [comment]
When you are login as a super admin then you can see 'search guard' menu on sidebar. First set secure guard plugin in elasticsearch then set 'searchguard.basicauth.forbidden_usernames: ["kibanaserver", "logstash"]'  on kibana.yml file then run restart elasticsearch and kibana. Now login as a elasticsearch credentials like user:admin and pwd: admin. Then you can see sidebar menu 'search guard' on kibana dashboard.
