### ISSUE TITLE
build tools

### ISSUE THREAD

**Issue by RichardLaing** [floragunncom/search-guard-kibana-plugin#47]
Hi there I am attempting to setup a build environment for version 5.6.4 what software is required to compile this item from the source code? I am currently running Ubuntu-16.04

**Comment by floragunncom** [comment]
<pre>
sudo apt-get update
sudo apt-get install nodejs npm zip git
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
</pre>

Open a new shell an run `./build.sh`

**Comment by jochenkressin** [comment]
You might also want to check out this tutorial from Tim Roes regarding building Kibana plugins: https://www.timroes.de/2015/12/02/writing-kibana-4-plugins-basics/
