### ISSUE TITLE
Support "View Dashboards Only mode"

### ISSUE THREAD

**Issue by rmcapote** [floragunncom/search-guard-kibana-plugin#48]
Hi, 

I am enjoying using Search Guard v.6 (beta). Nice work!
I am wondering if the next version will support the "[Kibana dashboard only mode](https://www.elastic.co/blog/kibana-dashboard-only-mode)" or if it is already supported and I missed how to configure it.

Regards,

**Comment by floragunncom** [comment]
this is planned and we are aware of it, thx

**Comment by rmcapote** [comment]
Ok ;) Thank you for your reply!

**Comment by jochenkressin** [comment]
We started working on this.

**Comment by marcosbis** [comment]
Have you got any updates on this feature ?
Thanks

**Comment by jochenkressin** [comment]
We're working on this currently, should not be long until release.

**Comment by sanky186** [comment]
By when is the release expected ? Or is it out already ?

**Comment by floragunncom** [comment]
very likely next week

**Comment by sanky186** [comment]
Hi Team, is the update containing readonly mode out ?

**Comment by jochenkressin** [comment]
Added in Search Guard v22 and Kibana Plugin v11: https://docs.search-guard.com/latest/changelog-6-x-22

**Comment by iahmad-khan** [comment]
Hi , 

Is there any documentation on how to setup the dashboard only mode through searchgaurd.

**Comment by sanky186** [comment]
Yes it has been updated in the documentation

**Comment by sanky186** [comment]
https://docs.search-guard.com/latest/kibana-read-only

**Comment by iahmad-khan** [comment]
got it , thanks

**Comment by sanky186** [comment]
Only Kibana yaml. you can add existing users to the Kibana yaml . And, they will turn read-only in Kibana 
Read-only rules in search guard are not for Kibana , they are for elastic.

**Comment by iahmad-khan** [comment]
but the documentation says nothing about users , it says about roles , so we can put roles in kibana yaml and then in searchguard config assign those roles to users?

**Comment by mgustafsson1** [comment]
Yes, you can define one or more read only roles in kibana.yml and then, in the config, make sure to assign one of those roles to the user(s) that should only be able to see the dashboard.
You could for example create a "sg_read_only" role and map it to any given user.

**Comment by iahmad-khan** [comment]
hi , 

its not working in my case:

in kibana.yml 

searchguard.readonly_mode.roles: ["sg_readonly1"]

in sg_internal_users file:


readall:
  hash: ycwzwvLtZxwZ82RmiEunBbIPiAmGZduB
  roles:
    - sg_readonly1

**Comment by floragunncom** [comment]
"roles:
- sg_readonly1"

This is a backend role, not a Search Guard role. You need to use the roles_mapping.yml to map a user or a backend role to a Search Guard role:

https://docs.search-guard.com/latest/mapping-users-roles

Use the authinfo endpoint to check the Search Guard roles of a user:

https://docs.search-guard.com/latest/demo-installer#testing-the-elasticsearch-installation

**Comment by iahmad-khan** [comment]
No luck.

I configured kibana , and elasticsearch accordingly then now can't access
anything with that user. no dashboards nothing , it can just login only and
then red permission errors everywhere.

If the docs are updated to add some step by step process , from creating a
user , role and then mapping for this specific case , will be very useful
and less confusing.

the current user that i have created , and the role , and mapping doesnt
work.

**Comment by iahmad-khan** [comment]
hi , 

any update?

Actually I want to hide all the controls on the kibana interface and let the users view the current dashboards only , is it possible with searchguard enterprise? and how to configure it.

**Comment by floragunncom** [comment]
@jochenkressin @mgustafsson1 can you have a look?

**Comment by jochenkressin** [comment]
Re-tested the dashboard mode, and everything seems to work as expected.

So to troubleshoot, I would suggest the following:

* Use a vanilla installation of Search Guard first, don't change any default users or roles
* Add the default sg_kibana_user user as readonly to kibana.yml:

`searchguard.readonly_mode.roles: ["sg_kibana_user"]`

* Restart Kibana and log in with kibanaro/kibanaro

This should give you the readonly mode. If this works, then you can try to apply it to your own roles, but please try this vanilly approach first.

The dashboard only mode is not an Enterprise feature, it should also work in the Community Version.

**Comment by iahmad-khan** [comment]
Hi,

I have many other read only users as well.

But I want a read only users that can only see current dashboards and can't
see other controls to explore data. That is dashboard only mode.

Is that something provided by searchguard?

**Comment by jochenkressin** [comment]
Yes, that's what I was talking about. The dashboard only mode is released, and for all our unit and integration tests it works fine. So to figure out why it does not work in your installation, please follow the steps I provided and try to set up the dashboard only mode with our demo roles first. If this works we can have a look why it is failing for your self-defined roles.

**Comment by floragunncom** [comment]
No, readonly mode will not work for 5.x.

**Comment by leviIM** [comment]
@jochenkressin hai, i follow this step.
##
Re-tested the dashboard mode, and everything seems to work as expected.

So to troubleshoot, I would suggest the following:

Use a vanilla installation of Search Guard first, don't change any default users or roles
Add the default sg_kibana_user user as readonly to kibana.yml:
searchguard.readonly_mode.roles: ["sg_kibana_user"]

Restart Kibana and log in with kibanaro/kibanaro
This should give you the readonly mode. If this works, then you can try to apply it to your own roles, but please try this vanilly approach first.

The dashboard only mode is not an Enterprise feature, it should also work in the Community Version.
##
but my kibana wont start, do you know what cause it?. i m using searchguard@6.3.1-14. 
Thanks

**Comment by bond-** [comment]
@floragunncom Currently our readonly users have access to Kibana Discover tab, is there a way to restrict which links are accessible?

**Comment by floragunncom** [comment]
Stay tuned, we will release soon something which gives you more control about users can see in Kibana and what not. Watch out in the google group forum or twitter for our announcements.
