### ISSUE TITLE
Cannot set the default index pattern after update to 5.6.4

### ISSUE THREAD

**Issue by alesnav** [floragunncom/search-guard-kibana-plugin#51]
Hello,

After updating ES and Kibana (and SearchGuard plugins, too) up to 5.6.4 from version 5.5.1, the Search Guard Kibana plugin cannot get the default index pattern for each Tenant. That default index pattern was configured before the update and everything worked as expected.

In our test environment, I have 4 Tenants, and none of them let me go to "Discover" menu and I am being redirected to the "Management" tab to set up a new index pattern or select one existant as the default one.

When I try to select one of them as the default index pattern, the following error is shown:

```
Config: Error 404 Not Found: [doc][config:5.6.4]: document missing: [document_missing_exception] [doc][config:5.6.4]: document missing, with { index_uuid="YogqxldBQI2HnwAI4RfJCg" & shard="0" & index=".kibana_113867_sia" }
```

I don't mind if I have to re-create all `.kibana_<ID>_<TENANT>`, but I don't know how to do it. By the way, the best option would be to set one of the index pattern as the default one...

My ES cluster is Green.

Can you please help me with this error?

Thanks,
Bets regards

**Comment by alesnav** [comment]
Well, I have finally deleted the whole .kibana_ID_TENANT index and it was recreated automatically some minutes after that.

The error was reproduced for two of our four tenants after the update, so maybe it is a small bug related to the upgrade process.

Thanks

**Comment by alesnav** [comment]
Hmmm, yes, it is still there. Every day, when I login to Kibana the first time, it throws an error showing that there is no default index pattern set. So, every day I have to set it again to be able to work with those Kibana tenants.

Thanks

**Comment by jochenkressin** [comment]
That's really strange. So just to make sure we understood the problem correctly:

-  You have 4 tenants, all of them have an index pattern set
- These tenants have been created with 5.5.1
- You updated to 5.6.4
- For all tenants you get the document missing exception

Then you deleted all tenant indices manually, and after they have been created, you are able to work with them. But when you log out and log in again, the document missing exception is back.

Is this the situation you are facing? Also, do you use the Global tenant? Can you post the content of your (non-tenant) .kibana index?

**Comment by jochenkressin** [comment]
@alesnav friendly ping

**Comment by alesnav** [comment]
Sorry @jochenkressin , I was forced to reinstall the cluster directly to 6.2 in other environment, so I cannot reproduce this issue.

As I can't give more info nor tests, I'm closing the issue.
