### ISSUE TITLE
 [Question]ELK 6.0.0 bug in chrome environment (wale, edge, explorer working)] SearchGuard6.0.0-17.beta1 and the default default setting has a hang phenomenon

### ISSUE THREAD

**Issue by D-ev** [floragunncom/search-guard-kibana-plugin#52]
**Kibana version**:
6.0.0

**Elasticsearch version**:
6.0.0

**Server OS version**:
CentOS 7.0

**Browser version**:
Chrome 62.0.3202.94

Search Guard 6.0.0-17.beta1 Operation Test 
-----
Basic login logic is  working, page pausing occurs on the dashboard.

**1. elasticsearch Search Guard Working**

![image](https://user-images.githubusercontent.com/34558656/34021932-b98f99a0-e17f-11e7-8cd7-1beb78d0b702.png)

**2. Kibana Search Guard paused after login**

has not Response 
----
![image](https://user-images.githubusercontent.com/34558656/34021961-e07f2c56-e17f-11e7-92bc-0a24dff7f8a0.png)

**Request URL is the same, but in 6.0.0 version, it is looped and there is no response value**

![image](https://user-images.githubusercontent.com/34558656/34022054-62bd1322-e180-11e7-8e12-ec2b9a9f10a8.png)

page not found message is normal.   
![image](https://user-images.githubusercontent.com/34558656/34022059-69dbbbfe-e180-11e7-9c93-7f5ac8628783.png)

Did I missing something..?

Regards, 
jinsu.

#

**Comment by jochenkressin** [comment]
I cannot reproduce the behavior. I get the 404 for non-existing index patterns and Kibana behaves normally. Is there anything in the Kibana logfiles? Is there anything in the Elasticsearch logfiles?

Also, which user are you using for logging in to Kibana? As far as I understood you just used the default configuration shipped with Search Guard, is this correct?

**Comment by floragunncom** [comment]
No feedback and not reproducible
