### ISSUE TITLE
SG GUI management panel overlapps

### ISSUE THREAD

**Issue by yasvanth** [floragunncom/search-guard-kibana-plugin#54]
Hi Team,
I am currently testing new SG 6 ( SG GUI) with elastic 6 and kibana 6. When I shrink the borwser I could see that panel overlap with the on the kibana menu as shown in the figure. When I maximize my browser it looks normal.

![screen shot 2017-12-20 at 16 19 43](https://user-images.githubusercontent.com/13409183/34217113-61c0ee32-e5a2-11e7-9a7f-d4821e894007.png)

Thanks,
Yash

**Comment by jochenkressin** [comment]
Thanks for reporting, we already fixed that and will include the fix in the GA release.

**Comment by yasvanth** [comment]
Hi @jochenkressin 
Thanks for your quick response. When adding user will it be possible to add the user to available roles by clicking on the roles ( dropdown) to add to the users.

Thanks,
Yash
![screen shot 2017-12-20 at 16 31 58](https://user-images.githubusercontent.com/13409183/34217538-a6251c78-e5a3-11e7-92d8-572b7f2c5235.png)

**Comment by jochenkressin** [comment]
At the moment the GUI reflects the way the configs are structured. For the next releases, we plan to improve and simplify the workflow. So yes, this will likely be added in one of the next releases of the Kibana plugin.

**Comment by jochenkressin** [comment]
Fixed in 6.1.0-8
