### ISSUE TITLE
Login inputfields on error

### ISSUE THREAD

**Issue by Sawadski** [floragunncom/search-guard-kibana-plugin#55]
**Kibana version:**
6.0.0

**Elasticsearch version:**
6.0.0

**Searchguard version:**
v6.0.0-6.beta1

**OS:**
macOS High Sierra

**Browser version:**
Chromium 54.0.2816.0 (64-bit)

Hi,
when I load the login page, both login fields (Username and Password) are immediately highlighted. 
Like in this screenshot:
<img width="1792" alt="pic" src="https://user-images.githubusercontent.com/22395273/34571891-25367bf6-f170-11e7-88df-babb908a6f50.png">

Thank you

**Comment by jochenkressin** [comment]
Fixed with v10 of the [Kibana](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.floragunn%22%20AND%20a%3A%22search-guard-kibana-plugin%22) plugin, released today.
