### ISSUE TITLE
Version 6.1.1

### ISSUE THREAD

**Issue by Sawadski** [floragunncom/search-guard-kibana-plugin#56]
Hi,

I want update my kibana to version 6.1.1. 
I saw that [search-guard](https://github.com/floragunncom/search-guard/releases/tag/ves-6.1.1-20.1) released the 6.1.1. 
Are there any plans to release this plugin in the upcoming days?

Thank you

**Comment by floragunncom** [comment]
The Kibana plugin 6.1.1. has been released on 30.12.2017 already:

https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22search-guard-kibana-plugin%22

**Comment by Sawadski** [comment]
Thank you for the quick response. 

I was confused because you have tagged and released the 6.1.0 version on github 
and I missed the 6.1.1 version.
