### ISSUE TITLE
Cannot access Searchguard GUI subsections if kibana serverPath is set

### ISSUE THREAD

**Issue by piercarlomacca** [floragunncom/search-guard-kibana-plugin#57]
I have kibana under Apache proxy like that
 
` ProxyPass /kibana http://localhost:5601
 ProxyPassReverse /kibana http://localhost:5601`

I conveniently put on my kibana.yml
`server.basePath: "/kibana"`

If I try to access to searchguard GUI subsections (role mappings, for example), I get the results in the screenshots.
![kibana-searchguard1](https://user-images.githubusercontent.com/33257506/35043169-dd88188e-fb8b-11e7-9a24-7abf0bf263cc.png)
![kibana-searchguard2](https://user-images.githubusercontent.com/33257506/35043172-e0b5279a-fb8b-11e7-877d-d3a1627a2217.png)

Everything works fine if I drop the proxy and start kibana without server.basePath.
I wasn't able to find anything regarding that in the docs, am I missing some configuration?

**Comment by floragunncom** [comment]
This might indeed be a bug, we'll check. Thanks for reporting!

**Comment by jochenkressin** [comment]
Fixed with v10 of the [Kibana](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.floragunn%22%20AND%20a%3A%22search-guard-kibana-plugin%22) plugin, released today.
