### ISSUE TITLE
plugin install failed

### ISSUE THREAD

**Issue by Ronnie08** [floragunncom/search-guard-kibana-plugin#63]
this is the log
  log   [02:40:33.012] [info][optimize] Optimizing and caching bundles for searchguard-multitenancy, searchguard-configuration, kibana, stateSessionStorageRedirect, timelion, searchguard-login and status_page. This may take a few minutes
Killed

after a few minutes，i got an killed error.
es version: 6.0.0
search-guard version ： search-guard-6-6.0.0-17.beta1
kibana version: kibana-6.0.0-linux-x86_64.tar
search-guard-kibana-plugin version：search-guard-kibana-plugin-6.0.0-6.beta1

any help?

**Comment by Ronnie08** [comment]
yes，without search guard plugin，it works normal

**Comment by jochenkressin** [comment]
The Kibana optimization process takes very long and consumes a lot of resources. I guess something is killing the process in the background due to this. The interesting question is, does that also happen when you install another heavy plugin, like X-Pack for example?

**Comment by floragunncom** [comment]
no feedback, assume solved
