### ISSUE TITLE
Can you change the timeout for LDAP logins?

### ISSUE THREAD

**Issue by fouts-bnet** [floragunncom/search-guard-kibana-plugin#68]
Hey there,

Can we change the timeout for LDAP logins? We're using Duo Proxy for MFA and it's doing a PUSH request to the user logging in, however unfortunately the timeout only seems to be like 2 seconds. Can we increase that to, say, 30 seconds?

https://duo.com/docs/ldap

If your clients allow you to configure the LDAP timeout, set them to values such that the clients will not give up for at least 60 seconds. This is necessary if your users choose to use Duo's out-of-band factors (phone callback, push) to log in, as the authentication proxy will not be able to respond to a LDAP authentication request until the user responds to the authentication challenge. If your clients do not allow you to configure the LDAP timeout behavior, then your users may be unable to authenticate with Duo's out-of-band factors.

**Comment by jochenkressin** [comment]
At the moment it's not possible to set the timeout via a config key. However, the implementation would be relatively straight-forward, so let me add this to our backlog. Which version of ES/SG are you using?

**Comment by jochenkressin** [comment]
This has been added to Search Guard 6.x-21 and 5.6.7-19, released today:

http://docs.search-guard.com/latest/active-directory-ldap-connection
http://docs.search-guard.com/latest/changelog-6-x-21
