### ISSUE TITLE
No active session to apply key to

### ISSUE THREAD

**Issue by gubr123** [floragunncom/search-guard-kibana-plugin#8]
Hi.

Using ES, kibana, search-guard and search-guard-kibana-plugin - All v5.2.1

Im trying to set new attribute in the session, with:

`request.auth.session.set('lastAccess', currentAccessTime);`

the result is an error:

>   log   [18:12:07.300] [error][searchguard] An error occurred while computing auth headers, clearing session: Error: No active session to apply key to

The request.auth.artifacts is undefined.

Any idea?

**Comment by floragunncom** [comment]
Try to set the value in hapi/auth.js#onPostAuth

**Comment by floragunncom** [comment]
No feedback, assume solved. If not pls. file a new issue.
