### ISSUE TITLE
Disable password autocomplete on login form

### ISSUE THREAD

**Issue by floragunncom** [floragunncom/search-guard-kibana-plugin#82]
See this forum post: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/search-guard/g3n_Y6zkVt8/frXX7sXhBQAJ

**Comment by jochenkressin** [comment]
Fixed with Search Guard v22 and Kibana Plugin v11: https://docs.search-guard.com/latest/changelog-6-x-22
