### ISSUE TITLE
Search Guard GUI not show in kibana 6.2.2

### ISSUE THREAD

**Issue by ming2020** [floragunncom/search-guard-kibana-plugin#84]
In elasticsearch.yml, i configure searchguard.restapi.roles_enabled: ["sg_all_access"] and in kibana when i access to the REST API it throw index_not_found_exception.
![qq 20180314101512](https://user-images.githubusercontent.com/15954271/37379880-c9e41b14-2770-11e8-95f6-77f953b613b9.png)

**Comment by ming2020** [comment]
![image](https://user-images.githubusercontent.com/15954271/37380311-145ae6d0-2773-11e8-9a49-ce18e4be406d.png)
authinfo can access

**Comment by floragunncom** [comment]
What version of SG do you run, Enterprise or Community?

**Comment by ming2020** [comment]
Community version.
![image](https://user-images.githubusercontent.com/15954271/37394190-315208e6-27ae-11e8-9bd8-9da556d63293.png)

**Comment by floragunncom** [comment]
The REST API is part of the Enterprise Edition and thus not available in the Community version. See the feature comparison table here: https://search-guard.com/product/

**Comment by ming2020** [comment]
Thank you very much.I'll pay for it.
