### ISSUE TITLE
Allowing anonymous access

### ISSUE THREAD

**Issue by sanacl** [floragunncom/search-guard-kibana-plugin#88]
The idea of this feature request is having an anonymous user which by default would be used by Kibana to query the database. Ideally this anonymous user would be part of the kibana.yml configuration.

The workflow would be:
* user with no credentials access Kibana
* Kibana checks a basic set of permissions (I guess read permission over the .kibana)
* if access granted: the menu on the right shows a "Log in" link instead of "Log out"
* if access is not granted, the log in form is displayed

**Comment by floragunncom** [comment]
possibly related to https://groups.google.com/d/msgid/search-guard/eafd0897-78ce-4022-9ecd-c810fed353b1%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by jochenkressin** [comment]
Kibana v16 has been released yesterday which fixes this issue.
