### ISSUE TITLE
Bad redirect after login ( proxypass apache + subdirectory )

### ISSUE THREAD

**Issue by willouuu** [floragunncom/search-guard-kibana-plugin#89]
Hi 
I have error, after login, redirect to http://monip/ instead of http://monip/kibana/ but the session is created

proxypass apache : 
```
<Location "/kibana/">
  ProxyPass "http://localhost:5601/"
  ProxyPassReverse "http://localhost:5601/kibana/"
</Location>
```

kibana.yml
`server.basePath: "/kibana"`

kibana.log : 

> {"type":"response","@timestamp":"2018-03-26T09:35:41Z","tags":[],"pid":16694,"method":"post","statusCode":200,"req":{"url":"/api/v1/auth/login","method":"post","headers":{"host":"localhost:5601","accept":"application/json, text/plain, */*","origin":"http://monip","kbn-version":"6.2.2","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36","content-type":"application/json;charset=UTF-8","dnt":"1","referer":"http://monip/kibana/login","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9,fr-FR;q=0.8,fr;q=0.7","x-forwarded-for":"myhostclient","x-forwarded-host":"monip","x-forwarded-server":"vhost.domain.fr","connection":"Keep-Alive","content-length":"39"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://monip/kibana/login"},"res":{"statusCode":200,"responseTime":11,"contentLength":9},"message":"POST /api/v1/auth/login 200 11ms - 9.0B"} 
> {"type":"response","@timestamp":"2018-03-26T09:35:41Z","tags":[],"pid":16694,"method":"get","statusCode":200,"req":{"url":"/api/v1/restapiinfo","method":"get","headers":{"host":"localhost:5601","accept":"application/json, text/plain, */*","kbn-version":"6.2.2","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36","dnt":"1","referer":"http://monip/kibana/login","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9,fr-FR;q=0.8,fr;q=0.7","x-forwarded-for":"myhostclient","x-forwarded-host":"monip","x-forwarded-server":"vhost.domain.fr","connection":"Keep-Alive"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://monip/kibana/login"},"res":{"statusCode":200,"responseTime":41,"contentLength":9},"message":"GET /api/v1/restapiinfo 200 41ms - 9.0B"} 

Version : search-guard-6:6.2.2-21

**Comment by ming2020** [comment]
![image](https://user-images.githubusercontent.com/15954271/38011343-a45f6658-328f-11e8-91a3-2548c49189cd.png)

this is my nginx config
you look like missing RewriteRule

**Comment by willouuu** [comment]
Hi,
Try to convert this rules to apache, but no changes 

```
<Location "/kibana">
  ProxyPass "http://localhost:5601"
  ProxyPassReverse "http://localhost:5601"
  RewriteRule "^/kibana/(.*)$" "/$1" [L,PT]
</Location>
```

I think make a rewrite rules is a hack, the redirection would have to consider basePath variable

Thanks

**Comment by willouuu** [comment]
I understand issue ! 

If go to http://ip/kibana/ redirect to http://ip/kibana/login?nextUrl=%2F#?_g=() and if go to http://ip/kibana/app/kibana/ redirect to  http://ip/kibana/login?nextUrl=%2Fapp%2Fkibana#?_g=()

Is it a issue or misuse?

**Comment by ming2020** [comment]
After change the `server.basePath` , have you reinstall search-guard-kibana-plugin?
delete the optimize folder and rebuild browser bundle, maybe it's work correct.

**Comment by willouuu** [comment]
Yes I installed the plugin after configuring Kibana

**Comment by willouuu** [comment]
Hummm I have this error on Kibana 6.2.3 : 

> Oops!
> Looks like something went wrong. Refreshing may do the trick.
> 
> Go back   Clear your session
>  Fatal Error
> Uncaught Error: Nav link for id = searchguard-configuration not found (http://myip/kibana/bundles/commons.bundle.js?v=16602:1)

I cleared the session but it didn't work.

Thanks

**Comment by floragunncom** [comment]
@jochenkressin @mgustafsson1 can you pls have a look?

**Comment by mgustafsson1** [comment]
@willouuu Regarding your error message "Nav link for id...":
Unfortunately I can't reproduce this. If the "searchguard-configuration" isn't available for whatever reason, the code that would trigger that error message is never called as far as I can see.

Did you try deleting the contents of the "optimize" folder and restarting Kibana, as ming2020 suggested?
In the Chrome developer tools, if you open the "Application" tab and click "Clear site data" - does that help?

**Comment by willouuu** [comment]
yes, deleting optimize folder work for "Nav link for id " error, but not resolv my first problem to bad redirect after logout

**Comment by jochenkressin** [comment]
Sorry to be late to the game here, but I can confirm that the "redirect-after-login" issue has been fixed with v12.

A simple test with a basepath "mybasepath":

nginx configuration:

`events {  }

http { 
  server {
    listen 5602;    
    location /mybasepath {
      proxy_redirect off;
      proxy_pass  http://localhost:5601/;
      rewrite ^/mybasepath/(.*)$ /$1 break;
    }
  }
}`

And in kibana.yml just:

`server.basePath: "/mybasepath"`

Seems to work just fine with v12. If I access:

`http://localhost:5602/mybasepath`

I get redirected to 

`http://localhost:5602/mybasepath/login`

And after successful login to 

`http://localhost:5602/mybasepath/app/kibana#/home?_g=()`

But in your last comment you wrote:

" ... but not resolv my first problem to bad **redirect after logout**"

Is this another issue ("logout") or is this a typo?

**Comment by jochenkressin** [comment]
@willouuu friendly pling

**Comment by willouuu** [comment]
I reinstall everything in version 6.2.4 and it works

Sorry for the inconvenience
