### ISSUE TITLE
Session timeout

### ISSUE THREAD

**Issue by senty** [floragunncom/search-guard-kibana-plugin#9]
Hi guys,

would it be possible to add configuration parameter for timeout (auto logout) ?

thank you very much !

**Comment by floragunncom** [comment]
We something like this already but its not yet documented. We will revise the docs soon.

**Comment by senty** [comment]
Thanks for response.
I will looking forward for revised docs !

**Comment by floragunncom** [comment]
With the upcoming beta-3, you can set:

searchguard.session.ttl: Session time to live in ms 
searchguard.session.keepalive: Whether to extend the session lifetime by session.ttl upon each request

See also: https://github.com/floragunncom/search-guard-docs/blob/master/kibana.md

**Comment by hackery** [comment]
Now here: https://docs.search-guard.com/latest/kibana-authentication#basic-authentication-configuration
